update: レスポンシブに対応
kurakke/nitkit-shot pull request #106
Opened 2023-10-29 04:57 UTC by n00bdy-noname

以下のissueのPRです。
#105 
一旦トップページのレスポンシブに対応しました。

2023-10-30 13:44 UTC, kai02221514 requested changes

2023-10-30 13:44 UTC, kai02221514 commented on src/components/rankingPage/DuoRankingName.tsx
> +    <div className='flex w-[13em] gap-x-[10px] md:w-full [&>p]:truncate'>
ここもwidthの指定で単位にemを指定してるのってなんでですかね？

2023-10-30 13:44 UTC, kai02221514 commented on src/components/rankingPage/RankingCard.tsx
> +        `shadow-ranking flex h-[38px] w-[100%] items-center rounded-[18px] border border-main p-[3px] font-main text-[15px]`,
`w-full`にしちゃっていいと思います!

2023-10-30 13:44 UTC, kai02221514 commented on src/components/topPage/Reservation/index.tsx
> +      <div className='mx-auto mt-[20px] flex w-fit md:pb-[+20px]'>
ここのプラスは消しちゃっていいと思います

2023-10-30 13:44 UTC, kai02221514 commented on src/components/rankingPage/index.tsx
> +        <ul className='mt-[10px] grid items-center gap-y-[10px] overflow-y-scroll'>
スクロールできてしまうのが気になると言っていたのでここは`overflow-y-hidden`にしてはどうでしょう？

2023-10-30 14:02 UTC, n00bdy-noname commented on src/components/layouts/DefaultLayout.tsx
> +        <main className='mt-[110px] h-full min-h-[calc(100vh_-_233px)] w-full px-[15px]'>
h-screenがheight: 100vhでスクリーンサイズなんですが、mt-[110px]とFooterの幅が追加されて要素が画面内に収まってても余白ができてスクロールできてしまうので、その二つの合計を引くことで高さの最小値をスクリーン幅ちょうどになるように設定してます。

2023-10-30 14:20 UTC, n00bdy-noname commented on src/components/rankingPage/DuoRankingName.tsx
> +    <div className='flex w-[13em] gap-x-[10px] md:w-full [&>p]:truncate'>
単位を変えながら調節していて、ちょうどいいものが13emでした。
確かに、よくよく考えたらここは可変じゃないのでpx指定で問題なさそうです。
変更しました。
788c802ef8a6612cbff0d903b8a5792d934db0b0

2023-10-30 14:24 UTC, n00bdy-noname commented on src/components/rankingPage/RankingCard.tsx
> +        `shadow-ranking flex h-[38px] w-[100%] items-center rounded-[18px] border border-main p-[3px] font-main text-[15px]`,
変更しました。
b9c705bbf2879b6f59fd9afca2aa87f327950433

2023-10-30 14:27 UTC, n00bdy-noname commented on src/components/topPage/Reservation/index.tsx
> +      <div className='mx-auto mt-[20px] flex w-fit md:pb-[+20px]'>
変更しました。
e64cf8d0b077e92e8acc4903424754e802a3153e

2023-10-30 14:31 UTC, n00bdy-noname commented on src/components/rankingPage/index.tsx
> +        <ul className='mt-[10px] grid items-center gap-y-[10px] overflow-y-scroll'>
変更しました。
91cda380cf89cd964d37ea5ad9dee14b068f46d8

2023-10-30 14:42 UTC, n00bdy-noname commented on src/components/general/GamingVisualContents.tsx
> +      )}
調整の対応しました。
4633dabeb99d04f69b429a4ced57864908c46bdd

2023-10-30 14:43 UTC, n00bdy-noname commented on src/components/layouts/DefaultLayout.tsx
> +        <main className='mt-[110px] h-full min-h-[calc(100vh_-_233px)] w-full px-[15px]'>
足されてる分を引いて、画面全体のサイズをスクリーンに合わせた感じです。

2023-10-31 01:36 UTC, kai02221514 submitted a review, later dismissed

2023-10-31 04:32 UTC, merged