Issue/19
kurakke/nitkit-shot pull request #20
Opened 2023-09-04 16:46 UTC by kurakke

Issue/19のタスクを行いました
カラーパレットに白を追加した上で、Footerコンポーネントを実装しました
レスポンシブにも対応させました
確認お願いします

2023-09-04 17:59 UTC, kai02221514 requested changes

2023-09-04 17:59 UTC, kai02221514 commented on src/components/Footer/index.tsx
> +                <div className="text-[10px] pt-[25px] pr-[4px] text-white">
ここのpadding-rightは7行目の親要素で設定したほうがいいかもです。

2023-09-04 17:59 UTC, kai02221514 commented on src/components/Footer/index.tsx
> +            <div className="bg-main h-[48px] pl-[15px] flex justify-between items-center rounded-[10px]">
roundedがFigmaでは5pxなので修正したほうがいいかもです。

2023-09-04 17:59 UTC, kai02221514 commented on src/components/Footer/index.tsx
> +        <div className="px-[15px] py-[12px]">
ここはmarginで設定したほうが意味合い的に正しいかもです。
なので、このタグを消して7行目のdivタグにmarginをつけてみてください。

[参考](https://zero-plus.io/media/margin-padding-difference/#:~:text=margin%E3%81%A8padding%E3%81%AE%E4%BD%BF%E3%81%84%E5%88%86%E3%81%91%E6%96%B9%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6%E3%81%BE%E3%81%A8%E3%82%81%E3%81%BE%E3%81%97%E3%81%9F,%E4%BD%9C%E3%82%8A%E3%81%9F%E3%81%84%E6%99%82%E3%81%AB%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B%E3%80%82)

2023-09-05 06:10 UTC, kai02221514 commented
Footerはデフォルトのコンポーネントなのでハンバーガメニューの変更内容をpullした後で、components/layoutsの中に入れておいてください。

[参考](https://zenn.dev/yodaka/articles/eca2d4bf552aeb)

2023-09-05 07:02 UTC, kurakke commented on src/components/Footer/index.tsx
> +            <div className="bg-main h-[48px] pl-[15px] flex justify-between items-center rounded-[10px]">
指摘の通り変更しました

2023-09-05 07:08 UTC, kurakke commented on src/components/Footer/index.tsx
> +                <div className="text-[10px] pt-[25px] pr-[4px] text-white">
指摘の通り変更しました

2023-09-05 07:37 UTC, kai02221514 commented
`import Image from 'next/image';
import React from 'react';

// eslint-disable-next-line import/no-unresolved
import logo from '../../../public/logo.png';

const Footer = (): JSX.Element => {
  return (
      <div className='bg-main m-[15px] h-[48px] pr-[4px] pl-[15px] flex justify-between items-center rounded-[5px]'>
        <Image src={logo} alt={'Logo'} height={44} width={120} />
        <div className='text-[10px] pt-[25px] text-white'>@ 2023 NitKit 4I.</div>
      </div>
  );
};

export default Footer;`

2023-09-05 11:19 UTC, kurakke commented on src/components/Footer/index.tsx
> +        <div className="px-[15px] py-[12px]">
指摘の通り変更しました

2023-09-05 13:32 UTC, merged