Issue/22
kurakke/nitkit-shot pull request #29
Opened 2023-09-06 07:08 UTC by kurakke

2023-09-06 12:30 UTC, kai02221514 requested changes

2023-09-06 12:30 UTC, kai02221514 commented on src/components/animation/hooks/useIntersection.tsx
> +export const useIntersection = <T extends HTMLElement>(
ここの型、違うファイルで二回使ってるので、可能ならtypes/に記述してインポートで使えるようにしてもいいかもしれません。

2023-09-06 12:30 UTC, kai02221514 commented on src/components/animation/hooks/useIntersection.tsx
> +  const [isIntersecting, setIsIntersecting] = useState(false);
型を明らかにしたほうがいいかもです。

2023-09-06 12:30 UTC, kai02221514 commented on src/components/animation/hooks/useIntersectionOnce.tsx
> +  const [isIntersected, setIsIntersected] = useState(false);
型を明らかにしたほうがいいかもです。

2023-09-06 12:56 UTC, kai02221514 commented
あとは特にないです。
コンフリクトの解決だけお願いします。

2023-09-06 14:26 UTC, kurakke commented on src/components/animation/hooks/useIntersection.tsx
> +  const [isIntersecting, setIsIntersecting] = useState(false);
型つけました

2023-09-06 14:27 UTC, kurakke commented on src/components/animation/hooks/useIntersectionOnce.tsx
> +  const [isIntersected, setIsIntersected] = useState(false);
型つけました

2023-09-07 03:15 UTC, kai02221514 approved these changes

2023-09-07 03:15 UTC, merged