トップページのInformation部分
kurakke/nitkit-shot pull request #30
Opened 2023-09-06 09:55 UTC by kurakke

2023-09-08 10:00 UTC, kai02221514 requested changes

2023-09-08 10:18 UTC, kai02221514 requested changes

2023-09-08 10:18 UTC, kai02221514 commented on src/components/topPage/information/index.tsx
informationをInformationにリネームしてください。

2023-09-08 11:06 UTC, kurakke commented on src/components/topPage/information/index.tsx
修正しました

2023-09-08 11:07 UTC, kurakke commented on src/components/topPage/information/index.tsx
> +  const informationText: InformationText[] = [
修正しました

2023-09-08 11:36 UTC, kurakke commented on src/components/topPage/information/index.tsx
> +        <div className='mt-[10px] flex h-[150px] w-[380px] flex-col items-center overflow-y-auto rounded border-2 border-accent-yellow pl-[4px] pt-[4px]'>
指摘の通り変更しました

2023-09-08 11:38 UTC, kurakke commented on src/components/topPage/information/index.tsx
> +        <div className='mt-[10px] flex h-[150px] w-[380px] flex-col items-center overflow-y-auto rounded border-2 border-accent-yellow pl-[4px] pt-[4px]'>
指摘の通り変更しました

2023-09-08 11:49 UTC, kurakke commented on src/components/topPage/information/index.tsx
修正しました

2023-09-08 11:50 UTC, kurakke commented on src/components/topPage/information/index.tsx
> +              <p className='font-main text-sm text-accent-yellow'>{text.date}</p>
指摘の通り修正しました

2023-09-08 11:54 UTC, kurakke commented on src/components/topPage/information/index.tsx
> +        <div className='mt-[10px] flex h-[150px] w-[380px] flex-col items-center overflow-y-auto rounded border-2 border-accent-yellow pl-[4px] pt-[4px]'>
指摘の通り修正しました

2023-09-08 11:56 UTC, kurakke commented on src/components/topPage/information/index.tsx
> +              <p className='ml-[8px] w-[280px] whitespace-pre-wrap break-words font-sub text-sm text-white'>
指摘の通り変更しました

2023-09-08 11:59 UTC, kurakke commented on src/components/topPage/information/index.tsx
> +            <div className='flex w-full whitespace-pre' key={text.date}>
指摘の通り修正しました

2023-09-08 13:02 UTC, kai02221514 commented
<image src="https://github.com/kurakke/nitkit-shot/assets/72437090/c6318980-a37a-4f13-9b17-c5c38d6df925" />

2023-09-10 04:36 UTC, kai02221514 approved these changes

2023-09-10 05:20 UTC, kai02221514 approved these changes
いいと思います！マージしましょう！

2023-09-10 05:24 UTC, merged