QandAページの実装
kurakke/nitkit-shot pull request #67
Opened 2023-10-19 02:46 UTC by n00bdy-noname

以下のissue番号のプルリクエストです。
#40 
QandAページを実装しました。

2023-10-19 12:32 UTC, kai02221514 requested changes

2023-10-19 12:32 UTC, kai02221514 commented on src/components/qAndAPage/QAndACard.tsx
> +    <div className='m-[20px] mx-auto w-[390px] rounded-[15px] border-[1px] border-accent-green bg-main p-[15px]'>
borderは標準で1pxなので`border-[1px]`を`border`に変えてください。

2023-10-19 12:32 UTC, kai02221514 commented on src/components/qAndAPage/QAndACard.tsx
> +          <li key={qAndACard.id} className='mx-[5px] my-[20px] font-main '>
ここの`my-[20px]`を消してください。

2023-10-19 12:32 UTC, kai02221514 commented on src/components/qAndAPage/QAndACard.tsx
> +      <ul>
ulのclassNameに`grid gap-y-[30px] mt-[20px]`を追加してください。

できた後に[これ](https://github.com/kurakke/nitkit-shot/pull/67/files#diff-8cad505c7c83795d3f30487ab28358918c36855915bc2f56ff33926a6fc5a5e2R22)をやってみてください。

2023-10-19 12:32 UTC, kai02221514 commented on src/components/qAndAPage/QAndACard.tsx
> +  qAndATitleJp: string;
好みの問題ですがここは多分`English`と`Japanese`を省略しない方がいいのと`japaneseQAndATitle`のような単語の順番にした方がいいと思います。

2023-10-19 12:32 UTC, kai02221514 commented on src/components/qAndAPage/QAndACard.tsx
> +    <div className='m-[20px] mx-auto w-[390px] rounded-[15px] border-[1px] border-accent-green bg-main p-[15px]'>
帳尻合わせのために`pb-[25px]`を追加してください。

2023-10-19 12:44 UTC, n00bdy-noname commented on types/QandA.ts
> +  title?: string;
コメントアウトでの対応で大丈夫ですか？

2023-10-19 12:56 UTC, kai02221514 commented on types/QandA.ts
> +  title?: string;
大丈夫です。
その場合上に役割を書いておいてください。

2023-10-19 12:58 UTC, n00bdy-noname commented on types/QandA.ts
> +  title?: string;
わかりました。

2023-10-19 13:29 UTC, n00bdy-noname commented on src/components/qAndAPage/QAndACard.tsx
> +        {Object.values(qAndA).map((qAndACard) => (
変更しました。
2cf6e7fc1987a052a63a17f702cedbdd698a2ee2

2023-10-19 13:30 UTC, n00bdy-noname commented on src/components/qAndAPage/QAndACard.tsx
> +    <div className='m-[20px] mx-auto w-[390px] rounded-[15px] border-[1px] border-accent-green bg-main p-[15px]'>
削除しました。
32637e28c0e74716b825e3cd9418c061a30292a6

2023-10-19 13:30 UTC, n00bdy-noname commented on src/components/qAndAPage/index.tsx
> +    <div className=''>
追加しました。
32637e28c0e74716b825e3cd9418c061a30292a6

2023-10-19 13:31 UTC, n00bdy-noname commented on src/components/qAndAPage/QAndACard.tsx
> +    <div className='m-[20px] mx-auto w-[390px] rounded-[15px] border-[1px] border-accent-green bg-main p-[15px]'>
変更しました。
f2c28c47282c5a40f0d1f4395385408e0f2e8220

2023-10-19 13:32 UTC, n00bdy-noname commented on src/components/qAndAPage/QAndACard.tsx
> +          <li key={qAndACard.id} className='mx-[5px] my-[20px] font-main '>
削除しました。
17e516590d9649de464e25c393b4df05575ea5c6

2023-10-19 13:32 UTC, n00bdy-noname commented on src/components/qAndAPage/QAndACard.tsx
> +      <ul>
追加しました。
17e516590d9649de464e25c393b4df05575ea5c6

2023-10-19 13:34 UTC, n00bdy-noname commented on src/components/qAndAPage/QAndACard.tsx
> +  qAndATitleJp: string;
変更しました。
54ba7e8d0f23e2167e4fc6b67704e22d7fb2e465

2023-10-19 13:38 UTC, n00bdy-noname commented on src/components/qAndAPage/QAndACard.tsx
> +    <div className='m-[20px] mx-auto w-[390px] rounded-[15px] border-[1px] border-accent-green bg-main p-[15px]'>
追加しました。
33d9cdb0a1e9acfcd05f9580a28f7a30fc4d838b

2023-10-19 13:45 UTC, kai02221514 commented on constants/qAndAMock.ts
> +import logo from '../public/logo.svg';
このimport今のところ使ってないので削除して大丈夫です

2023-10-19 13:52 UTC, n00bdy-noname commented on constants/qAndAMock.ts
> +import logo from '../public/logo.svg';
削除しました。
7a9946c951d2bc7851af8dbc5a2f5c1e5d9723c6

2023-10-19 14:06 UTC, kai02221514 requested changes

2023-10-19 14:29 UTC, n00bdy-noname commented on src/components/qAndAPage/QAndACard.tsx
> +            <p className='mt-[5px] text-[14px] text-accent-yellow'>A. {qAndAContents.answer}</p>
実装例に沿って修正を行いました。
bb85464fe2fa87ad767a4df25a442a268058524e

2023-10-19 14:45 UTC, n00bdy-noname commented on constants/qAndAMock.ts
Notionに追加された項目を追加し、改行タグ'\n'を追加

2023-10-19 14:46 UTC, n00bdy-noname commented on constants/qAndAMock.ts
Notionに追加された項目を追加し、改行タグ'\n'を追加

2023-10-19 14:47 UTC, n00bdy-noname commented on src/components/qAndAPage/index.tsx
whitespace-pre-lineを追加し、改行タグに対応

2023-10-19 14:48 UTC, n00bdy-noname commented on constants/qAndAMock.ts
> +  },
Notionに追加された項目を追加し、改行タグ'\n'を追加

2023-10-19 14:50 UTC, n00bdy-noname commented on constants/qAndAMock.ts
> +  },
Notionに追加された項目を追加し、改行タグ'\n'を追加

2023-10-19 14:51 UTC, n00bdy-noname commented on constants/qAndAMock.ts
> +};
Notionに追加された項目を追加し、改行タグ'\n'を追加

2023-10-23 07:17 UTC, kai02221514 submitted a review, later dismissed

2023-10-23 07:57 UTC, kurakke commented on src/components/qAndAPage/index.tsx
lintかかってますか？

2023-10-23 07:57 UTC, kurakke commented on src/components/qAndAPage/QAndACard.tsx
> +          <li key={qAndAContents.id} className='mx-[5px] font-main'>
liタグにmx当てるよりもulタグでpx当てた方がいいと思います

2023-10-23 07:57 UTC, kurakke commented on types/QandA.ts
interfaceかtypeかどっちかに統一しましょう

2023-10-23 13:36 UTC, kai02221514 commented on types/QandA.ts
ファイル名の命名規則の話？

2023-10-23 13:37 UTC, kurakke commented on types/QandA.ts
ファイル内のinterfaceとexport typeしてるところの話です

2023-10-23 17:20 UTC, n00bdy-noname commented on src/components/qAndAPage/QAndACard.tsx
> +          <li key={qAndAContents.id} className='mx-[5px] font-main'>
変更しました。
9b9161a93f9329542913609954bac727f4fe4973

2023-10-23 17:42 UTC, n00bdy-noname commented on types/QandA.ts
変更しました。
72676df073b652478c8cd5cd7c9aa93455a0f899
9babbb526e29ba0920ee5b066780cb681279d4b2

2023-10-23 17:50 UTC, n00bdy-noname commented on src/components/qAndAPage/index.tsx
const内のQAndACardについて

ゲーム内容と予約は改行されますが、その他は改行してもフォーマットすると一行にされます。謎です。

2023-10-23 17:53 UTC, n00bdy-noname commented on src/components/qAndAPage/index.tsx
> +      <QAndACard englishQAndATitle='Other' japaneseQAndATitle='その他' qAndA={OTHER_MOCK} />
上2つのQAndACardは改行されるが、最後のだけ一行でフォーマットされる。

2023-10-24 01:16 UTC, kurakke commented on src/components/qAndAPage/index.tsx
> +      <QAndACard englishQAndATitle='Other' japaneseQAndATitle='その他' qAndA={OTHER_MOCK} />
ならOK

2023-10-24 01:16 UTC, merged